name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        id: build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: ./dist

      - name: Deploy via SCP
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          ssh-keyscan ${{ secrets.IP_ADDRESS }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key_pair_dra_fabiola_martins && chmod 600 ~/.ssh/key_pair_dra_fabiola_martins
          scp -r -i ~/.ssh/key_pair_dra_fabiola_martins ./dist/* ${{ secrets.USERNAME }}@${{ secrets.IP_ADDRESS }}:/var/www/drafabiolamartins.com.br
